# Utiliza la imagen oficial de Node.js
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /node-app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Expone el puerto que el servidor Node.js utilizará
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "start"]